### ISSUE TITLE
Create test environment

### ISSUE THREAD

**Issue by sanderdejong88** [FrontMen/fm-hours#104]

**Comment by DeanMW** [comment]
I've done some reading into this and it seems as though it hasnt really changed in the last 3 years, It looks like you still need to set up a separate project to have a dev/prod environment:

https://firebase.google.com/docs/projects/multiprojects

https://stackoverflow.com/questions/37450439/separate-dev-and-prod-firebase-environment

Resources to valid this. If this is an acceptable approach I will begin with this.

**Comment by DeanMW** [comment]
https://github.com/FrontMen/fm-hours/pull/119

This is now in a PR, the firebase env can be located here: 

https://console.firebase.google.com/u/1/project/fm-hours-dev

***NOTE***
This new env does NOT include the functions as there are a paid for feature, as far as Im aware these will not be needed in the future either, except maybe the email function? which Im not sure is necessary for the development env anyway
