### ISSUE TITLE
as employee: focus on hours input

### ISSUE THREAD

**Issue by sstraatemans** [FrontMen/fm-hours#129]
when I focus an hours input, it does not select the already filled in "0".
So when I type 8. It will say 24 hours. 

would prefer to select the whole value. so that when I type 8, the new value will be 8.

**Comment by sanderdejong88** [comment]
This was fixed a while back. We'll have a look 👍

**Comment by vladPinteaFrontmen** [comment]
@sanderdejong88 @sstraatemans can confirm, the value is selected on focus and overwritten. It takes a double click or other weird combinations to created the described effect

**Comment by vladPinteaFrontmen** [comment]
Checked with @sstraatemans and the bug is no longer reproducing. Closing the ticket
