### ISSUE TITLE
as employee: the current date is disabled.

### ISSUE THREAD

**Issue by sstraatemans** [FrontMen/fm-hours#131]
So I can never fill in the hours of today

**Comment by kimvermeer** [comment]
Same here, but I can also not fill in yesterday (June 30)
![image](https://user-images.githubusercontent.com/7124130/124097352-c9f3a880-da5b-11eb-9c1c-6cd9bad926d9.png)

**Comment by sstraatemans** [comment]
Ok.it's not the date of today.
It seems that for some people from the 30th of June on, all dates are disabled. 
It's now July 1st. and we can't fill in the 30th of June or later.
my project is Eneco. 
Kim's project is Rabobank, I guess.

**Comment by sanderdejong88** [comment]
Putting on top of the sprint.

**Comment by YejunWu168** [comment]
So the issue is that the data in the firestore is incorrect, the employee's affected like Steven and Kim both have an end date at june 29th

**Comment by YejunWu168** [comment]
I will add an extra field for the admins to modify employee's end date
