### ISSUE TITLE
Download month overview

### ISSUE THREAD

**Issue by vladPinteaFrontmen** [FrontMen/fm-hours#169]
As an employee, from the month overivew, I want to download my overview in pdf format. 

It should contain my filters, so I can filter out only the desired projects to add to it. 

This ticket is about enhncing the current pdf, @matthiasdeboer should test and specifiy any desired changes

**Comment by sanderdejong88** [comment]
@vladPinteaFrontmen isn't this fixed already?

**Comment by matthiasdeboer** [comment]
No further feedback from users, seems to be all good
