### ISSUE TITLE
404 error when changing weeks in admin view

### ISSUE THREAD

**Issue by DunkVader** [FrontMen/fm-hours#259]
In timesheets admin view - when viewing another users weekly timesheet you will get a 404 error if you click the "next" or "previous" week button.

I suspect it has something to do with the routing since it is different when viewing another user in admin view. i.e `timesheets/{employeeId}/{timestamp}` vs normal view `records/`

**Comment by Cool-ka** [comment]
already solved by refactoring the code by Dean
