### ISSUE TITLE
Test worklogs API

### ISSUE THREAD

**Issue by sanderdejong88** [FrontMen/fm-hours#268]
https://confluence.hosted-tools.com/display/TL/API

Yes, hier kan je de nodige endpoints en documentatie vinden: https://documenter.getpostman.com/view/7200955/TzJu9HaY
testing: https://bridge.testing.intracto.com/api/v1/

Mss een kleine verduidelijking wat het verschil is bij de create en update tussen met/zonder "using source". De create zal altijd een id teruggeven, mochten jullie deze niet bij jullie intern opslaan om later mutaties op te doen zou je kunnen opteren om de "using source" endpoints te werken. Dan kan je op basis van de meegegeven source en source id (waar source bv frontmen-timeapp kan zijn) en source id jullie interne id is.

**Comment by sanderdejong88** [comment]
Contact me to get the API secret needed to talk to the API

**Comment by sanderdejong88** [comment]
Still need to check how to see if we submit the right thing. There is probably a test environment of the finance system but haven't checked yet.

**Comment by raulfdm** [comment]
## Description in English

Yes, you can find the necessary endpoints and documentation here: https://documenter.getpostman.com/view/7200955/TzJu9HaY
testing: https://bridge.testing.intracto.com/api/v1/

Maybe a little clarification on what the difference is with create and update between with/without "using source". The create will always return an id, if you don't store it internally to make changes later you could opt to work the "using source" endpoints. Then you can based on the supplied source and source id (where source can be eg frontmen-timeapp) and source id is your internal id.

**Comment by sanderdejong88** [comment]
API for reading contracts:
https://jira.hosted-tools.com/browse/BRIDGE-4219
