### ISSUE TITLE
Fix typo/spelling mistake

### ISSUE THREAD

**Issue by ZakKa89** [FrontMen/fm-hours#273]
![image](https://user-images.githubusercontent.com/24491661/131342785-d2d0b44e-454b-4494-b3ab-30857c7de4df.png)

Ilness should be Illness :-)

**Comment by sanderdejong88** [comment]
Should be Sick leave

**Comment by raulfdm** [comment]
@sanderdejong88 I think this is a database string, right? I couldn't find in the project.

Also:
- I don't have access to production data base
- I can't login in production (tried 10 times in a row and no success)
<img width="511" alt="Screenshot 2021-09-14 at 16 45 01" src="https://user-images.githubusercontent.com/12464600/133279604-28275e68-f410-4953-b655-bef864380e8a.png">

**Comment by Corsico** [comment]
it's in db yes, but the change will not propagate to old entries cos it's not built that way. I can update it
